### ISSUE TITLE
Tried adding it to plugins, then invalid yml error comes up in console

### ISSUE THREAD

**Issue by axemwa** [InventivetalentDev/ReflectionHelper#10]
The title pretty much explains it "Tried adding it to plugins, then invalid yml error comes up in console"

**Comment by InventivetalentDev** [comment]
This is an API. You use this in your code by importing it, not adding it to your plugins folder.

**Comment by axemwa** [comment]
Sorry my bad know any good guides to do this?

**Comment by InventivetalentDev** [comment]
https://maven.apache.org/
